### ISSUE TITLE
Error on running sample

### ISSUE THREAD

**Issue by vandanphadke** [marcliberatore/mallet-lda#3]
I tried out the sample which you have given in the README. The sample gives an error message and stops indefinitely. I am attaching the code and the error log below, 

Code:
`(let [data [[1 ["a" "little" "lamb"]]
              [2 ["row" "your" "boat"]]
              [3 ["boat" "river" "dance"]]]
      instance-list (make-instance-list data)]
  (lda instance-list))`

Output:

Couldn't open cc.mallet.util.MalletLogger resources/logging.properties file.
 Perhaps the 'resources' directories weren't copied into the 'class' directory.
 Continuing.
Feb 02, 2017 7:46:27 PM cc.mallet.topics.ParallelTopicModel <init>
INFO: Coded LDA: 10 topics, 4 topic bits, 1111 topic mask
Feb 02, 2017 7:46:27 PM cc.mallet.topics.ParallelTopicModel initializeHistograms

INFO: max tokens: 3
Feb 02, 2017 7:46:27 PM cc.mallet.topics.ParallelTopicModel initializeHistograms

INFO: total tokens: 9
Feb 02, 2017 7:46:28 PM cc.mallet.topics.ParallelTopicModel estimate
INFO: <10> LL/token: -4.54015
Feb 02, 2017 7:46:28 PM cc.mallet.topics.ParallelTopicModel estimate
INFO: <20> LL/token: -4.54015
Feb 02, 2017 7:46:29 PM cc.mallet.topics.ParallelTopicModel optimizeBeta
INFO: [beta: 0]
Feb 02, 2017 7:46:29 PM cc.mallet.topics.ParallelTopicModel modelLogLikelihood
WARNING: NaN in log likelihood calculation
Feb 02, 2017 7:46:29 PM cc.mallet.topics.ParallelTopicModel estimate
INFO: <30> LL/token: 0
java.lang.ArrayIndexOutOfBoundsException: -1
        at cc.mallet.topics.WorkerRunnable.sampleTopicsForOneDoc(WorkerRunnable.
java:489)
        at cc.mallet.topics.WorkerRunnable.run(WorkerRunnable.java:275)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

After which the execution stops but the program does not exit the process. I waited for like 3 hrs to see if it actually finishes the process, but it didn't.

**Comment by marcliberatore** [comment]
Are you working with a cloned copy of the repository, or a downloaded JAR?

**Comment by Hendekagon** [comment]
it's caused by insufficent input data - it works when you run it on a large text
